config/routes.rb
Cornerstone::Engine.routes.draw do

  resources :discussions, :except => [:show] do
    resources :posts, :only => [:create, :edit, :update, :destroy]
  end

  # Custom routes to handle show for discussions and discussion categories
  get "/discussions/:category/:id" => "discussions#show", :as => "category_discussion"
  get "/discussions/:category" => "discussions#category", :as => "discussions_category"

  # Custom routes for knowledge base
  get "/knowledge/:category/:id" => "knowledgebase#show", :as => "category_article"
  get "/knowledge/:category" => "knowledgebase#category", :as => "articles_category"
  get "/knowledge/" => "knowledgebase#index", :as => "knowledge_base"

  root :to => "help#index"

  namespace :admin do
    root :to => "admin#dashboard"
    resources :categories, :except => :show
    resources :articles
    resources :discussions, :only => [:edit, :update]
  end

end

app/models/cornerstone/article.rb
module Cornerstone
  class Article < ActiveRecord::Base
    # == CONSTANTS == #

    # == ASSOCIATIONS == #
    belongs_to :category, :counter_cache => :item_count

    # == ACCESSIBILITY == #
    # == SCOPES == #

    # == VALIDATIONS == #
    validates_presence_of :title, :body, :category

    # == CALLBACKS == #
    # == CLASS METHODS == #
    # == INSTANCE METHODS == #

  end
end

app/models/cornerstone/category.rb
module Cornerstone
  class Category < ActiveRecord::Base

    # == CONSTANTS == #
    TYPES = ["Discussion", "Article"]

    # == ASSOCIATIONS == #
    has_many :discussions, :dependent => :destroy
    has_many :articles, :dependent => :destroy

    # == ACCESSIBILITY == #
    attr_accessible :name, :category_type, :description

    # == SCOPES == #

    scope :discussions, lambda { where("cornerstone_categories.category_type = 'Discussion'") }
    scope :articles, lambda { where("cornerstone_categories.category_type = 'Article'") }

    # == VALIDATIONS == #
    validates :name, :presence => true,
                     :length => {:maximum => 50}

    validates :category_type, :inclusion => { :in => Cornerstone::Category::TYPES }

    validates :description, :presence => true,
                            :length => {:maximum => 500}

    # == CALLBACKS == #
    # == CLASS METHODS == #

    # == INSTANCE METHODS == #

    # Provides the latest discussion created for this category
    def latest_discussion
      latest_discussions(1).first
    end

    # Provides the last 'num' discussions created for this category
    def latest_discussions(num=nil)
      Discussion.latest_for_category(self, num)
    end

  end
end

app/models/cornerstone/discussion.rb
module Cornerstone
  class Discussion < ActiveRecord::Base

    # == CONSTANTS == #
    STATUS = Cornerstone::Config.discussion_statuses

    # == ASSOCIATIONS == #
    belongs_to :category, :counter_cache => :item_count
    # belongs_to 'user' also established by acts_as_cornerstone_user

    has_many :posts, :dependent => :destroy
    accepts_nested_attributes_for :posts

    # == ACCESSIBILITY == #
    attr_accessible :subject, :privte, :category_id, :posts_attributes

    # == SCOPES == #
    default_scope :order => "created_at DESC",
                  :conditions => {:privte => false}

    scope :latest_for_category, lambda { |cat, num=5|
                                         where(:category_id => cat.id)
                                         .limit(num) }

    # == VALIDATIONS == #
    validates :subject, :presence => true,
                        :length => { :maximum => 50 }

    validates :status, :inclusion => { :in => Cornerstone::Discussion::STATUS }

    validates :category, :presence => true

    # == CALLBACKS == #
    after_save :set_latest_discussion

    # == CLASS METHODS == #

    # == INSTANCE METHODS == #
    def author_name
      self.posts.first.author_name
    end

    # returns true if discussion is 'closed'
    def closed?
      self.status == Cornerstone::Discussion::STATUS.last
    end

    # returns true if it was created by given user or if given user is an admin
    def created_by?(check_user)
      return false unless check_user.present?
      return true if check_user.cornerstone_admin?
      self.user && self.user == check_user
    end

    # returns an array of participants for the discussion
    def participants(exclude_email=nil)
      ps = []
      self.posts.each do |p|
        if p.author_name && p.author_email
          ps << [p.author_name, p.author_email]
        end
      end
      ps.delete_if{|p| p[1] == exclude_email}.uniq
    end

    # return a nicely formatted string for emailing
    # i.e. Name <email_address>, Name <email_address>
    def participants_email_list(exclude_email=nil)
      participants(exclude_email).collect{ |p| "#{p[0]} <#{p[1]}>" }.join(", ")
    end

    #######
    private
    #######

    # Update the category's latest discussion author/date
    def set_latest_discussion
      post = self.posts.last
      if post
        cat = self.category
        cat.latest_discussion_author = post.author_name
        cat.latest_discussion_date = Time.now.to_s(:db)
        cat.save
      end
    end


  end

end

app/models/cornerstone/post_observer.rb
module Cornerstone
  class PostObserver < ActiveRecord::Observer

    def after_create(post)
      discussion = post.discussion
      if discussion.posts.count == 1
        # If first post (i.e. start of new discussion), email admin list
        CornerstoneMailer.new_discussion(post, discussion).deliver

        # Also email user of the first post to let them know all is good.
        CornerstoneMailer.new_discussion_user(post, discussion).deliver
      else
        # If not first post, email participants of discussion

        # do not email the author of this newly created post
        discussion.participants(post.author_email).each do |p|
          CornerstoneMailer.new_post(p[0], p[1], post, discussion).deliver
        end
      end
    end

  end
end

app/controllers/cornerstone/admin/application_controller.rb
module Cornerstone
  class Admin::ApplicationController < ::ApplicationController
    authorize_cornerstone_admin!

  end
end

app/controllers/cornerstone/admin/articles_controller.rb
module Cornerstone
  class Admin::ArticlesController < Admin::ApplicationController

    respond_to :html

    def index
      @articles = Article.all
      respond_with(:admin, @articles)
    end

    def show
      @article = Article.find(params[:id])
      respond_with(:admin, @article)
    end

    # GET /cornerstone/admin/articles/new
    def new
      @article = Article.new
      @categories = Category.articles
      respond_with(:admin, @articles)
    end

    # POST /cornerstone/admin/articles/
    def create
      @article = Article.new(params[:article])
      if @article.save
        flash[:notice] = 'Article was successfully created.'
      else
        @categories = Category.articles
      end
      respond_with(:admin, @article)
    end

    # GET /cornerstone/admin/articles/:id/edit
    def edit
      @article = Article.find(params[:id])
      @categories = Category.articles
      respond_with(:admin, @article)
    end

    # PUT /cornerstone/admin/articles/:id
    def update
      @article = Article.find(params[:id])
      if @article.update_attributes(params[:article])
        flash[:notice] = 'Article was successfully updated.'
      else
        @categories = Category.articles
      end
      respond_with(:admin, @article)
    end

    # DELETE /cornerstone/admin/articles/:id
    def destroy
      @article = Article.find(params[:id])
      flash[:notice] = 'Article was successfully destroyed.' if @article.destroy
      respond_with(:admin, @article, :location => admin_articles_path)
    end

  end
end

app/controllers/cornerstone/admin/categories_controller.rb
module Cornerstone
  class Admin::CategoriesController < Admin::ApplicationController

    respond_to :html

    def index
      @discussion_categories = Category.discussions
      @article_categories = Category.articles
    end

    # GET /cornerstone/admin/categories/new
    def new
      @category = Category.new
      respond_with(:admin, @category)
    end

    # POST /cornerstone/admin/categories/
    def create
      @category = Category.new(params[:category])
      flash[:notice] = 'Category was successfully created.' if @category.save
      respond_with(:admin, @category, :location => admin_categories_path)
    end

    # GET /cornerstone/admin/categories/:id/edit
    def edit
      @category = Category.find(params[:id])
      respond_with(:admin, @category)
    end

    # PUT /cornerstone/admin/categories/:id
    def update
      @category = Category.find(params[:id])
      flash[:notice] = 'Category was successfully updated.' if @category.update_attributes(params[:category])
      respond_with(:admin, @category, :location => admin_categories_path)
    end

    # DELETE /cornerstone/admin/categories/:id
    def destroy
      @category = Category.find(params[:id])
      flash[:notice] = 'Category was successfully destroyed.' if @category.destroy
      respond_with([:admin, @category], :location => admin_categories_path)
    end

  end
end

app/controllers/cornerstone/admin/discussions_controller.rb
module Cornerstone
  class Admin::DiscussionsController < Admin::ApplicationController

    respond_to :html

    # GET /cornerstone/admin/discussions/:id/edit
    def edit
      @discussion = Discussion.includes(:posts => :user).find(params[:id])
      @categories = Category.discussions
      respond_with(:admin, @discussion)
    end

    # PUT /cornersone/admin/discussions/:id
    def update
      @discussion = Discussion.includes(:posts => :user).find(params[:id])

      respond_with(@discussion.category, @discussion) do |format|
        if @discussion.update_attributes(params[:discussion])
          flash[:notice] = "Discussion was successfully updated."
          format.html {redirect_to category_discussion_path(@discussion.category, @discussion)}
        else
          @categories = Category.discussions
          format.html {render :edit}
        end
      end

    end


  end
end

app/controllers/cornerstone/application_controller.rb
module Cornerstone
  class ApplicationController < ActionController::Base

  end
end

app/controllers/cornerstone/articles_controller.rb
module Cornerstone
  class ArticlesController < ApplicationController
    authorize_cornerstone_admin!

    respond_to :html

    def index
      @articles = Article.all
      respond_with(@articles)
    end

    def show
      @article = Article.find(params[:id])
      respond_with(@article)
    end

    # GET /cornerstone/articles/new
    def new
      @article = Article.new
      @categories = Category.articles
      respond_with(@articles)
    end

    # POST /cornerstone/articles/
    def create
      @article = Article.new(params[:article])
      if @article.save
        flash[:notice] = 'Article was successfully created.'
      else
        @categories = Category.articles
      end
      respond_with(@article)
    end

    # GET /cornerstone/articles/:id/edit
    def edit
      @article = Article.find(params[:id])
      @categories = Category.articles
      respond_with(@article)
    end

    # PUT /cornerstone/articles/:id
    def update
      @article = Article.find(params[:id])
      if @article.update_attributes(params[:article])
        flash[:notice] = 'Article was successfully updated.'
      else
        @categories = Category.articles
      end
      respond_with(@article)
    end

    # DELETE /cornerstone/articles/:id
    def destroy
      @article = Article.find(params[:id])
      flash[:notice] = 'Article was successfully destroyed.' if @article.destroy
      respond_with(@article, :location => articles_path)
    end

  end
end

app/controllers/cornerstone/discussions_controller.rb
module Cornerstone
  class DiscussionsController < ApplicationController

    respond_to :html

    # GET /cornerstone/discussions/
    def index
      @categories = Category.discussions
    end

    # GET /cornerstone/discussions/new
    def new
      @categories = Category.discussions
      @category = Category.find(params[:cat]) if params[:cat]
      @discussion = Discussion.new
      @discussion.category_id = @category.id if @category
      @discussion.posts.build
      respond_with(@discussion)
    end

    # GET /cornerstone/discussions/:category
    def category
      @category = Category.includes(:discussions => :posts).find(params[:category])
      @discussions = @category.discussions
      respond_with(@discussions, :template => "cornerstone/discussions/categorical_index")
    end

    # GET /cornerstone/discussions/:category/:id
    def show
      @discussion = Discussion.includes(:posts => :user).find(params[:id])
      @new_post = Post.new
      @posts = @discussion.posts
    end

    # POST /cornerstone/discussions/
    def create
      @discussion = Discussion.new(params[:discussion])

      # assign user if signed in
      if current_cornerstone_user
        @discussion.user = current_cornerstone_user
        @discussion.posts.first.user = current_cornerstone_user
      end

      respond_with(@discussion.category, @discussion) do |format|
        if @discussion.save
          flash[:notice] = 'Discussion was successfully created.'
          format.html {redirect_to category_discussion_path(@discussion.category, @discussion)}
        else
          @categories = Category.discussions
          format.html {render :new}
        end
      end
    end

  end
end

app/controllers/cornerstone/help_controller.rb
module Cornerstone
  class HelpController < ApplicationController

    # GET /
    def index
      @discussion_categories = Category.select("name, item_count").discussions
    end

  end
end

app/controllers/cornerstone/knowledgebase_controller.rb
module Cornerstone
  class KnowledgebaseController < ApplicationController
    respond_to :html

    # GET /knowledge/
    def index
      @categories = Category.articles
    end

    # GET /cornerstone/knowledge/:category
    def category
      @category = Category.includes(:articles).find(params[:category])
      @articles = @category.articles
      respond_with(@articles, :template => "cornerstone/knowledgebase/categorical_index")
    end

    # GET /cornerstone/knowledge/:category/:id
    def show
      @article = Article.find(params[:id])
    end

  end
end

app/controllers/cornerstone/posts_controller.rb
module Cornerstone
  class PostsController < ApplicationController
    respond_to :html

    # POST /cornerstone/discussions/:discussion_id/posts
    def create
      @discussion = Discussion.includes(:posts => :user).find(params[:discussion_id])
      existing_posts = @discussion.posts.dup
      @post = @discussion.posts.new(params[:post])

      # assign user if signed in
      if current_cornerstone_user
        @post.user = current_cornerstone_user
      end
            
      respond_with(@discussion, @post) do |format|
        if @post.save
          # close discussion if commit param dictates
          unless params[:comment_close].nil?
            @discussion.update_attribute(:status, Discussion::STATUS.last)
          else
            # re-open discussion if discussion is closed
            if @discussion.closed?
              @discussion.update_attribute(:status, Discussion::STATUS.first)
            end
          end

          flash[:notice] = 'Comment was successfully created.'
          format.html {redirect_to category_discussion_path(@discussion.category, @discussion)}
        else
          @new_post = @post
          @posts = existing_posts
          format.html {render :template => "cornerstone/discussions/show"}
        end
      end
    end
    
    # GET /cornerstone/discussions/:discussion_id/posts/:id/edit
    def edit
      @post = Post.includes(:user, :discussion).find(params[:id])
      raise Cornerstone::AccessDenied unless @post.created_by?(current_cornerstone_user)
      @discussion = @post.discussion
      respond_with(@discussion, @post)
    end

    # PUT /cornerstone/discussions/:discussion_id/posts/:id
    def update
      @post = Post.includes(:user, :discussion).find(params[:id])
      raise Cornerstone::AccessDenied unless @post.created_by?(current_cornerstone_user)
      @discussion = @post.discussion
      flash[:notice] = "Post was successfully updated." if @post.update_attributes(params[:post])
      respond_with(@discussion, @post, :location => category_discussion_path(@discussion.category, @discussion))
    end
    
    # DELETE /cornerstone/discussions/:discussion_id/posts/:id
    def destroy
      @post = Post.includes(:user, :discussion).find(params[:id])
      raise Cornerstone::AccessDenied unless @post.created_by?(current_cornerstone_user)
      @discussion = @post.discussion
      flash[:notice] = "Post was successfully deleted." if @post.destroy
      respond_with(@discussion, @post, :location => category_discussion_path(@discussion.category, @discussion))
    end

  end
end

app/helpers/cornerstone/application_helper.rb
module Cornerstone
  module ApplicationHelper

  end
end

app/helpers/cornerstone/discussions_helper.rb
module Cornerstone
  module DiscussionsHelper

    # Returns details and links about the latest discussion for a given category
    def latest_discussion_details(category)
      if discussion = category.latest_discussion
        render :partial => 'latest_discussion', :object => discussion,
                                                :locals => {:category => category}
      else
        "N/A"
      end
    end

  end
end

app/views/cornerstone/discussions/_discussion.html.erb
<tr>
  <td><%= link_to discussion.subject, category_discussion_path(category, discussion),
                                      :title => discussion.subject %>
      by <%= discussion.author_name %>
  </td>
  <td><%= discussion.status %></td>
  <td><%= discussion.reply_count %></td>
  <td><%= discussion.latest_post_date %>
      by <%= discussion.latest_post_author %>
  </td>
</tr>

app/views/cornerstone/discussions/_discussion_category.html.erb
<tr>
  <td>
    <%= link_to discussion_category.name, discussions_category_path(discussion_category),
                                 :title => discussion_category.name %>
    <span class="discussion_category_description"><%= discussion_category.description %></span>
  </td>
  <td>
    <%= discussion_category.item_count %>
  </td>
  <td>
    <%= latest_discussion_details(discussion_category) %>
  </td>
</tr>

app/views/cornerstone/discussions/_form.html.erb
<%= form_for(form_path) do |f| %>
  <%= render :partial => 'cornerstone/shared/errors',
             :locals => {:rails_model => @discussion} %>

  <div class="field">
    <%= f.label "Private" %><%= f.check_box :privte %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.collection_select :category_id, @categories, :id, :name,
                                          :prompt => "Please select a category" %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>

  <%= f.fields_for :posts, @discussion.posts.first do |p| %>
    <%= render :partial => 'cornerstone/posts/fields', :locals => {:p => p} %>
  <% end %>

  <% if cornerstone_admin? %>
    <div class="field">
      <%= f.label :status %><br />
      <%= f.select :status, Cornerstone::Discussion::STATUS %> 
    </div> 
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/cornerstone/discussions/_latest_discussion.html.erb
<%= link_to latest_discussion.created_at, discussion_path(category, latest_discussion),
                                          :title => latest_discussion.subject %>
by <%= category.latest_discussion_author %>

app/views/cornerstone/discussions/categorical_index.html.erb
<h1>Discussions for <%= @category.name.titleize %></h1>
<p><%= @category.description %></p>
<table id="discussions">
  <tr>
    <th>Discussion</th>
    <th>State</th>
    <th>Replies</th>
    <th>Latest Post</th>
  </tr>
  <% unless @discussions.empty? %>
    <%= render :partial => "discussion", :collection => @discussions,
                                         :locals => {:category => @category} %>
  <% else %>
    <tr>
      <td>There are no discussions yet, be the first to ask something!</td>
      <td>N/A</td>
      <td>N/A</td>
      <td>N/A</td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Discussion', new_discussion_path(:cat => @category),
                              :title => "New Discussion" %>

app/views/cornerstone/discussions/edit.html.erb
<h1>Editing Discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', [@category, @discussion] %> |
<%= link_to 'Back', discussions_path %>

app/views/cornerstone/discussions/index.html.erb
<h1>Listing Discussion Categories</h1>

<p>Welcome to the discussion area. You can read and reply to other people's discussions, or create your own discussion in one of the following categories.</p>

<table id="discussion_categories">
  <tr>
    <th>Category</th>
    <th>Discussion Count</th>
    <th>Latest Discussion</th>
  </tr>
  <% unless @categories.empty? %>
    <%= render :partial => "discussion_category", :collection => @categories %>
  <% else %>
    <tr>
      <td>There are no categories yet.</td>
      <td>N/A</td>
      <td>N/A</td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Discussion', new_discussion_path, :title => "New Discussion" %>

app/views/cornerstone/discussions/new.html.erb
<h1>New Discussion</h1>

<%= render :partial => 'form', :locals => {:form_path => @discussion} %>

<%= link_to 'Back', discussions_path %>

app/views/cornerstone/discussions/show.html.erb
TODO: Insert BreadCrumbs

<h1><%= @discussion.subject %></h1>

<% if @discussion.privte %>
  <p>This discussion is private.</p>
<% end %>

<p><b>Status:</b> <%= @discussion.status %></p>
<table id="discussion_posts">
<%= render :partial => "cornerstone/posts/post", :collection => @posts, 
           :locals => {:discussion => @discussion} %>
</table>

<div id="reply_form">
<%= render :partial => "cornerstone/posts/form", :locals => {:post => @new_post,
                                                             :discussion => @discussion} %>
</div>