config/routes.rb
Cornerstone::Engine.routes.draw do

  resources :discussions, :except => [:show] do
    resources :posts, :only => [:create, :edit, :update, :destroy]
  end

  # Custom routes to handle show for discussions and discussion categories
  get "/discussions/:category/:id" => "discussions#show", :as => "category_discussion"
  get "/discussions/:category" => "discussions#category", :as => "discussions_category"

  # Custom routes for knowledge base
  get "/knowledge/:category/:id" => "knowledgebase#show", :as => "category_article"
  get "/knowledge/:category" => "knowledgebase#category", :as => "articles_category"
  get "/knowledge/" => "knowledgebase#index", :as => "knowledge_base"

  root :to => "help#index"

  namespace :admin do
    root :to => "admin#dashboard"
    resources :categories, :except => :show
    resources :articles
    resources :discussions, :only => [:edit, :update]
  end

end

app/models/cornerstone/article.rb
module Cornerstone
  class Article < ActiveRecord::Base
    # == CONSTANTS == #

    # == ASSOCIATIONS == #
    belongs_to :category, :counter_cache => :item_count

    # == ACCESSIBILITY == #
    # == SCOPES == #

    # == VALIDATIONS == #
    validates_presence_of :title, :body, :category

    # == CALLBACKS == #
    # == CLASS METHODS == #
    # == INSTANCE METHODS == #

  end
end

app/controllers/cornerstone/admin/articles_controller.rb
module Cornerstone
  class Admin::ArticlesController < Admin::ApplicationController

    respond_to :html

    def index
      @articles = Article.all
      respond_with(:admin, @articles)
    end

    def show
      @article = Article.find(params[:id])
      respond_with(:admin, @article)
    end

    # GET /cornerstone/admin/articles/new
    def new
      @article = Article.new
      @categories = Category.articles
      respond_with(:admin, @articles)
    end

    # POST /cornerstone/admin/articles/
    def create
      @article = Article.new(params[:article])
      if @article.save
        flash[:notice] = 'Article was successfully created.'
      else
        @categories = Category.articles
      end
      respond_with(:admin, @article)
    end

    # GET /cornerstone/admin/articles/:id/edit
    def edit
      @article = Article.find(params[:id])
      @categories = Category.articles
      respond_with(:admin, @article)
    end

    # PUT /cornerstone/admin/articles/:id
    def update
      @article = Article.find(params[:id])
      if @article.update_attributes(params[:article])
        flash[:notice] = 'Article was successfully updated.'
      else
        @categories = Category.articles
      end
      respond_with(:admin, @article)
    end

    # DELETE /cornerstone/admin/articles/:id
    def destroy
      @article = Article.find(params[:id])
      flash[:notice] = 'Article was successfully destroyed.' if @article.destroy
      respond_with(:admin, @article, :location => admin_articles_path)
    end

  end
end

app/controllers/cornerstone/articles_controller.rb
module Cornerstone
  class ArticlesController < ApplicationController
    authorize_cornerstone_admin!

    respond_to :html

    def index
      @articles = Article.all
      respond_with(@articles)
    end

    def show
      @article = Article.find(params[:id])
      respond_with(@article)
    end

    # GET /cornerstone/articles/new
    def new
      @article = Article.new
      @categories = Category.articles
      respond_with(@articles)
    end

    # POST /cornerstone/articles/
    def create
      @article = Article.new(params[:article])
      if @article.save
        flash[:notice] = 'Article was successfully created.'
      else
        @categories = Category.articles
      end
      respond_with(@article)
    end

    # GET /cornerstone/articles/:id/edit
    def edit
      @article = Article.find(params[:id])
      @categories = Category.articles
      respond_with(@article)
    end

    # PUT /cornerstone/articles/:id
    def update
      @article = Article.find(params[:id])
      if @article.update_attributes(params[:article])
        flash[:notice] = 'Article was successfully updated.'
      else
        @categories = Category.articles
      end
      respond_with(@article)
    end

    # DELETE /cornerstone/articles/:id
    def destroy
      @article = Article.find(params[:id])
      flash[:notice] = 'Article was successfully destroyed.' if @article.destroy
      respond_with(@article, :location => articles_path)
    end

  end
end

app/views/cornerstone/admin/articles/_article.html.erb
<tr>
  <td><%= link_to article.title, [:admin, article] %></td>
  <td><%= l(article.updated_at) %></td>
  <td><%= link_to "Edit", edit_admin_article_path(article) %></td>
  <td><%= link_to 'Destroy', [:admin, article], :confirm => 'Are you sure?',
                                                          :method => :delete,
                                                          :title => "Destroy" %>
</tr>

app/views/cornerstone/admin/articles/_form.html.erb
<%= form_for([:admin, @article]) do |f| %>
  <%= render :partial => "cornerstone/shared/errors", :locals => {:rails_model => @article} %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.collection_select :category_id, @categories, :id, :name,
                                          :prompt => "Please select a category" %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/cornerstone/admin/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @article] %> |
<%= link_to 'Back', admin_articles_path %>

app/views/cornerstone/admin/articles/index.html.erb
<h1>Listing Articles</h1>

<table id="articles">
  <tr>
    <th>Title</th>
    <th>Updated At</th>
    <th></th>
    <th></th>
  </tr>
  <% unless @articles.empty? %>
    <%= render :partial => "article", :collection => @articles %>
  <% else %>
    <tr>
      <td>There are no articles yet.</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Article', new_admin_article_path, :title => "New Article" %>

app/views/cornerstone/admin/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_articles_path %>

app/views/cornerstone/admin/articles/show.html.erb
<h1><%= @article.title %></h1>

<%= @article.body %>